version: 0.2

phases:    
  build:
    commands:
      - npm install
      - cd client 
      - npm install
  
artifacts:
  files:
   - '**/*'
   - dist/**/*
   - node_modules/**/*
   - Scripts/**/*
   
cache:
  paths:
    - './node_modules/**/*'